In [1]:
import numpy as np

In [3]:
a = np.arange(3, 10)
print(a)
print(type(a))

[3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [13]:
b = np.linspace(1, 10, 5)
print(b)

[ 1.    3.25  5.5   7.75 10.  ]


In [14]:
c = np.zeros(5)
print(c)

[0. 0. 0. 0. 0.]


In [15]:
d = np.ones(5)
print(d)

[1. 1. 1. 1. 1.]


In [46]:
np.random.seed(0)
e = np.random.rand(7)
print(e)
f = np.random.randn(5)
print(f)
g = np.random.randn(5)
print(g)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721]
[ 1.26611853 -0.50587654  2.54520078  1.08081191  0.48431215]
[ 0.57914048 -0.18158257  1.41020463 -0.37447169  0.27519832]


In [55]:
h = np.eye(4)
h

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
i = np.array([1, 2, 3])
j = i.copy()
j = j * 2
print(i)
print(j)

[1 2 3]
[2 4 6]


In [87]:
k = np.array([1, 3, 2])
l = np.array([-1, 3, 1])

In [90]:
print(k + l)
print(k - l)
print(k * l)
l.sort()
print(l)

[0 4 5]
[ 2  2 -1]
[-1  3  6]
[-1  1  3]


In [76]:
print(k == l)

[False  True False]


In [77]:
print(k > l)

[ True False  True]


In [85]:
np.random.seed(10)
m = np.around(np.random.rand(100), 4)
print(m.ndim)
print(m.size)
print(m.shape)
print(m.max())
print(m.min())
print(np.mean(m)) # Average
print(np.median(m))
print(np.std(m)) # Standard Deviation

1
100
(100,)
0.9876
0.0039
0.48534800000000006
0.49675
0.27497057750966736


In [91]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [92]:
print(n.T) #np.transpose(n)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [98]:
# k = np.array([1, 3, 2])
# l = np.array([-1, 1, 3])
# o = [1, 3, 2, -1, 3, 1]
o = np.concatenate((k, l))
print(o)

[ 1  3  2 -1  1  3]
